version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vinland-app
    container_name: vinland_app
    restart: always
    volumes:
      - .:/var/www
    networks:
      - vinland_net

  web:
    image: nginx:alpine
    container_name: vinland_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vinland_net

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: TFG
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - vinland_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - vinland_net

volumes:
  db_data:

networks:
  vinland_net:
